gvcf_path: '/data/mcgaugheyd/projects/nei/mcgaughey/NA12878/validate_snakemake/gvcfs'
output_name: 'PICK_A_NAME'
picard_version:  'picard/2.9.2'
pedigree: 'HG001_WGS.ped'
phase_by_transmission: 'No'
gatk_version: 'GATK/3.5-0'
ref_genome: '/fdb/GATK_resource_bundle/b37-2.8/human_g1k_v37_decoy.fasta'
# if VQSR set to 'yes', then VQSR is run with below truth / training sets
# if set to 'no', then hard filtering used
VQSR: 'no'
# VQSR
hapmap: '-resource:hapmap,known=false,training=true,truth=true,prior=15.0 /fdb/GATK_resource_bundle/b37-2.8/hapmap_3.3.b37.vcf'
omni: '-resource:omni,known=false,training=true,truth=true,prior=12.0 /fdb/GATK_resource_bundle/b37-2.8/1000G_omni2.5.b37.vcf'
1000G: '-resource:1000G,known=false,training=true,truth=false,prior=10.0 /fdb/GATK_resource_bundle/b37-2.8/1000G_phase1.snps.high_confidence.b37.vcf'
dbsnp: '-resource:dbsnp,known=true,training=false,truth=false,prior=2.0 /fdb/GATK_resource_bundle/b37-2.8/dbsnp_138.b37.vcf'
mills: '-resource:mills,known=false,training=true,truth=true,prior=12.0 /fdb/GATK_resource_bundle/b37-2.8/Mills_and_1000G_gold_standard.indels.b37.vcf'
SNP_tranche: '99.97'
INDEL_tranche: '99.97'
# hard filter
filterExpression_SNP: '--filterExpression \"QD < 2.0 || FS > 60.0 || MQ < 30.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0\"'
filterExpression_INDEL: '--filterExpression \"QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0\"'
